# Generated by Django 4.1.5 on 2023-04-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantSignUpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_heading', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=1000)),
                ('applications_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterSignUpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
