# Generated by Django 4.1.5 on 2023-05-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_applicant_job_recruiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user_password',
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.CharField(default='some string', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='password',
            field=models.CharField(default='some string', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='username',
            field=models.CharField(default='some string', max_length=50),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.CharField(default='some string', max_length=50),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='password',
            field=models.CharField(default='some string', max_length=50),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='username',
            field=models.CharField(default='some string', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(default='some string', max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(default='some string', max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.CharField(default='some string', max_length=50),
        ),
    ]
