# Generated by Django 4.1.5 on 2023-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_remove_applicant_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsAppliedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=0)),
                ('applicant_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='some', max_length=50)),
                ('email', models.CharField(default='some', max_length=50)),
                ('message', models.CharField(default='some', max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='applications_count',
            new_name='recruiter_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_posted_by',
        ),
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.CharField(default='some string', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='some string', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='rep',
            field=models.CharField(default='some string', max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='some string', max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='time_posted',
            field=models.CharField(default='some string', max_length=20),
        ),
    ]
